name: python-env-pmdata
# channels priority see https://bioconda.github.io/ conda-forge has highest prioriy
channels: 
- defaults 
- bioconda 
- conda-forge 
dependencies: 
- python>=3.7 
- numpy 
- pandas 
- r
- r-irkernel
